version: '2'
services:
    imst1app-app:
        image: imst1app
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://imst1app-mysql:3306/imst1app?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    imst1app-mysql:
        extends:
            file: mysql.yml
            service: imst1app-mysql
